### ISSUE TITLE
Improve language identifiers in copyright/license spreadsheet

### ISSUE THREAD

**Issue by mmartin9684-sil** [BibleNLP/ebible-corpus#2]
1. A number of Bibles don't have a language name associated with them in the copyright/license spreadsheet, including: eng-Brenton, eng-web, eng-webbe, eng-web-c, engwebp, engwebpb, engwmb, engwmbb.
2. Consider adding an ISO-639 language identifier for each resource, in addition to the language name.  This might make it a little easier to correlate the corpus file names with the copyright/license file entries.
3. Consider including the corpus file names in the spreadsheet.

**Comment by davidbaines** [comment]
Added three columns to the spreadsheet to include the ISO 639-3 language code, the language name in English and the Autonym where available.

There's a language names sheet too for looking up the language name in English.
